/*
 * Copyright (C) 2026 Huawei Technologies Co., Ltd.
 * SPDX-License-Identifier: MIT
 *
 * Legacy event-name compatibility aliases.
 */
#ifndef COLDTRACE_EVENT_ALIASES_H
#define COLDTRACE_EVENT_ALIASES_H

#include <dice/events/annotate_rwlock.h>
#include <dice/events/cxa.h>
#include <dice/events/pthread.h>

#ifndef EVENT_THREAD_EXIT
    #define EVENT_THREAD_EXIT EVENT_PTHREAD_EXIT
#endif
#ifndef EVENT_THREAD_CREATE
    #define EVENT_THREAD_CREATE EVENT_PTHREAD_CREATE
#endif
#ifndef EVENT_THREAD_JOIN
    #define EVENT_THREAD_JOIN EVENT_PTHREAD_JOIN
#endif
#ifndef EVENT_MUTEX_LOCK
    #define EVENT_MUTEX_LOCK EVENT_PTHREAD_MUTEX_LOCK
#endif
#ifndef EVENT_MUTEX_TIMEDLOCK
    #define EVENT_MUTEX_TIMEDLOCK EVENT_PTHREAD_MUTEX_TIMEDLOCK
#endif
#ifndef EVENT_MUTEX_TRYLOCK
    #define EVENT_MUTEX_TRYLOCK EVENT_PTHREAD_MUTEX_TRYLOCK
#endif
#ifndef EVENT_MUTEX_UNLOCK
    #define EVENT_MUTEX_UNLOCK EVENT_PTHREAD_MUTEX_UNLOCK
#endif
#ifndef EVENT_MUTEX_CLOCKLOCK
    #define EVENT_MUTEX_CLOCKLOCK EVENT_PTHREAD_MUTEX_CLOCKLOCK
#endif
#ifndef EVENT_COND_WAIT
    #define EVENT_COND_WAIT EVENT_PTHREAD_COND_WAIT
#endif
#ifndef EVENT_COND_TIMEDWAIT
    #define EVENT_COND_TIMEDWAIT EVENT_PTHREAD_COND_TIMEDWAIT
#endif
#ifndef EVENT_COND_SIGNAL
    #define EVENT_COND_SIGNAL EVENT_PTHREAD_COND_SIGNAL
#endif
#ifndef EVENT_COND_BROADCAST
    #define EVENT_COND_BROADCAST EVENT_PTHREAD_COND_BROADCAST
#endif
#ifndef EVENT_COND_CLOCKWAIT
    #define EVENT_COND_CLOCKWAIT EVENT_PTHREAD_COND_CLOCKWAIT
#endif
#ifndef EVENT_RWLOCK_RDLOCK
    #define EVENT_RWLOCK_RDLOCK EVENT_PTHREAD_RWLOCK_RDLOCK
#endif
#ifndef EVENT_RWLOCK_TIMEDRDLOCK
    #define EVENT_RWLOCK_TIMEDRDLOCK EVENT_PTHREAD_RWLOCK_TIMEDRDLOCK
#endif
#ifndef EVENT_RWLOCK_TRYRDLOCK
    #define EVENT_RWLOCK_TRYRDLOCK EVENT_PTHREAD_RWLOCK_TRYRDLOCK
#endif
#ifndef EVENT_RWLOCK_WRLOCK
    #define EVENT_RWLOCK_WRLOCK EVENT_PTHREAD_RWLOCK_WRLOCK
#endif
#ifndef EVENT_RWLOCK_TIMEDWRLOCK
    #define EVENT_RWLOCK_TIMEDWRLOCK EVENT_PTHREAD_RWLOCK_TIMEDWRLOCK
#endif
#ifndef EVENT_RWLOCK_TRYWRLOCK
    #define EVENT_RWLOCK_TRYWRLOCK EVENT_PTHREAD_RWLOCK_TRYWRLOCK
#endif
#ifndef EVENT_RWLOCK_UNLOCK
    #define EVENT_RWLOCK_UNLOCK EVENT_PTHREAD_RWLOCK_UNLOCK
#endif
#ifndef EVENT_SPIN_LOCK
    #define EVENT_SPIN_LOCK EVENT_PTHREAD_SPIN_LOCK
#endif
#ifndef EVENT_SPIN_TRYLOCK
    #define EVENT_SPIN_TRYLOCK EVENT_PTHREAD_SPIN_TRYLOCK
#endif
#ifndef EVENT_SPIN_UNLOCK
    #define EVENT_SPIN_UNLOCK EVENT_PTHREAD_SPIN_UNLOCK
#endif
#ifndef EVENT_CXA_GUARD_ACQUIRE
    #define EVENT_CXA_GUARD_ACQUIRE EVENT___CXA_GUARD_ACQUIRE
#endif
#ifndef EVENT_CXA_GUARD_RELEASE
    #define EVENT_CXA_GUARD_RELEASE EVENT___CXA_GUARD_RELEASE
#endif
#ifndef EVENT_CXA_GUARD_ABORT
    #define EVENT_CXA_GUARD_ABORT EVENT___CXA_GUARD_ABORT
#endif
#ifndef EVENT_ANNOTATE_RWLOCK_CREATE
    #define EVENT_ANNOTATE_RWLOCK_CREATE EVENT_ANNOTATERWLOCKCREATE
#endif
#ifndef EVENT_ANNOTATE_RWLOCK_DESTROY
    #define EVENT_ANNOTATE_RWLOCK_DESTROY EVENT_ANNOTATERWLOCKDESTROY
#endif
#ifndef EVENT_ANNOTATE_RWLOCK_ACQ
    #define EVENT_ANNOTATE_RWLOCK_ACQ EVENT_ANNOTATERWLOCKACQUIRED
#endif
#ifndef EVENT_ANNOTATE_RWLOCK_REL
    #define EVENT_ANNOTATE_RWLOCK_REL EVENT_ANNOTATERWLOCKRELEASED
#endif

#endif /* COLDTRACE_EVENT_ALIASES_H */
