#!/bin/sh
COLDTRACE_ROOT="$(readlink -f $(dirname $(readlink -f $0))/..)"
COLDTRACE_BUILD="$COLDTRACE_ROOT/build"
PRELOAD="$COLDTRACE_BUILD/src/libcoldtrace.so"

export TSANO_LIBDIR="$COLDTRACE_BUILD/deps/dice/deps/tsano"
TSANO="$COLDTRACE_ROOT/deps/dice/deps/tsano/tsano"

exec $TSANO env LD_PRELOAD="$PRELOAD" "$@"
