#!/bin/sh

COLDTRACE_ROOT="$(readlink -f $(dirname $(readlink -f $0))/..)"
if [ -z "$COLDTRACE_BUILD" ]; then
  if [ -n "$GN_OUT_DIR" ]; then
    COLDTRACE_BUILD="$COLDTRACE_ROOT/$GN_OUT_DIR"
  else
    COLDTRACE_BUILD="$COLDTRACE_ROOT/build"
  fi
fi
PRELOAD="$COLDTRACE_BUILD/test/libtrace_checker.so"
if [ -z "$TSANO_LIBDIR" ]; then
  if [ -f "$COLDTRACE_BUILD/libtsano.so" ]; then
    TSANO_LIBDIR="$COLDTRACE_BUILD"
  else
    TSANO_LIBDIR="$COLDTRACE_BUILD/deps/dice/deps/tsano"
  fi
fi
export TSANO_LIBDIR
TSANO="$COLDTRACE_ROOT/deps/dice/deps/tsano/tsano"
export COLDTRACE_PATH=/tmp/traces
export COLDTRACE_MAX_FILES=3
export COLDTRACE_TRACE_SIZE=4096
export COLDTRACE_DISABLE_COPY=true
exec $TSANO env LD_PRELOAD="$PRELOAD" "$@"
