#!/bin/sh
COLDTRACE_SCRIPTS="$(readlink -f $(dirname $(readlink -f $0)))"
COLDTRACE_ROOT="$(readlink -f $COLDTRACE_SCRIPTS/..)"
if [ -z "$COLDTRACE_BUILD" ]; then
  COLDTRACE_BUILD="$COLDTRACE_ROOT/build"
fi
PRELOAD="$COLDTRACE_BUILD/src/libcoldtrace.so"

if [ -z "$TSANO_LIBDIR" ]; then
  if [ -f "$COLDTRACE_BUILD/libtsano.so" ]; then
    TSANO_LIBDIR="$COLDTRACE_BUILD"
  else
    TSANO_LIBDIR="$COLDTRACE_BUILD/deps/dice/deps/tsano"
  fi
fi
export TSANO_LIBDIR
TSANO="$COLDTRACE_ROOT/deps/dice/deps/tsano/tsano"

args=""
ensure_traces=""

while [ "$#" -gt 0 ]; do
	case "$1" in
	-ensure-traces)
		ensure_traces=true
		;;
	*)
		args="${args} $1"
		;;
	esac
	shift
done

if [ -z "$ensure_traces" ]; then
	exec $TSANO env LD_PRELOAD="$PRELOAD" "${args}"
else
	# run as child process and check traces dir non empty
	set -e
	echo "COLDTRACE_PATH=$COLDTRACE_PATH"
	$TSANO env \
		COLDTRACE_PATH="$COLDTRACE_PATH" \
		LD_PRELOAD="$PRELOAD" \
		"${args}"
	$COLDTRACE_SCRIPTS/traces-nonempty.sh "$COLDTRACE_PATH"
fi
