#!/bin/sh

COLDTRACE_ROOT="$(readlink -f $(dirname $(readlink -f $0))/..)"
if [ -z "$COLDTRACE_BUILD" ]; then
  COLDTRACE_BUILD="$COLDTRACE_ROOT/build"
fi
PRELOAD="$COLDTRACE_BUILD/test/libtrace_checker.so"
if [ -z "$TSANO_LIBDIR" ]; then
  TSANO_LIBDIR="$COLDTRACE_BUILD"
fi
export TSANO_LIBDIR
TSANO="$COLDTRACE_ROOT/deps/dice/deps/tsano/tsano"
export COLDTRACE_PATH=/tmp/traces
export COLDTRACE_MAX_FILES=3
export COLDTRACE_TRACE_SIZE=4096
export COLDTRACE_DISABLE_COPY=true
exec $TSANO env LD_PRELOAD="$PRELOAD" "$@"
