name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Submodule dice and libvsync
      run: git submodule update --init  
    - name: Configure
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build
    - name: Upload deps folder
      uses: actions/upload-artifact@v4
      with:
        name: deps-folder
        path: deps/dice/deps/tsano
    - name: Upload libtsano folder
      uses: actions/upload-artifact@v4
      with:
        name: build-tsano-folder
        path: build/deps/dice/deps/tsano/
    - name: Upload tests folder
      uses: actions/upload-artifact@v4
      with:
        name: tests-folder
        path: test
    - name: Upload scripts folder
      uses: actions/upload-artifact@v4
      with:
        name: scripts-folder
        path: scripts/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download scripts folder
      uses: actions/download-artifact@v4
      with:
        name: scripts-folder
        path: scripts/
    - name: Download libtsano folder
      uses: actions/download-artifact@v4
      with:
        name: build-tsano-folder
        path: build/deps/dice/deps/tsano/
    - name: Download tests folder
      uses: actions/download-artifact@v4
      with:
        name: tests-folder
        path: test/
    - name: Download deps folder
      uses: actions/download-artifact@v4
      with:
        name: deps-folder
        path: deps/dice/deps/tsano
    - name: Where am I?
      run: find .

    - name: Create testing workspace folder
      run: mkdir testing_workspace

    - name: Modify execute rights to scripts
      run: |
        chmod 777 scripts/coldtracer
        chmod 777 scripts/trace_dump.py
        chmod 777 deps/dice/deps/tsano/tsano
        chmod 777 build/deps/dice/deps/tsano/libtsano.so

    - name: Run simple_malloc_test
      run:  |
        gcc test/simple_malloc_test.c -fsanitize=thread -o testing_workspace/simple_malloc_test
        COLDTRACE_PATH=testing_workspace/simple_malloc_trace scripts/coldtracer testing_workspace/simple_malloc_test
        scripts/trace_dump.py testing_workspace/simple_malloc_trace/freezer_log_1_0.bin | grep "234" | grep "Allocated 234B of memory"
        scripts/trace_dump.py testing_workspace/simple_malloc_trace/freezer_log_1_0.bin | grep "432" | grep "Allocated 432B of memory"

    
