name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fetch
      run: git submodule update --init  
    - name: Configure
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build
