name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Submodule dice and libvsync
      run: git submodule update --init  
    - name: Configure
      run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build
    - name: Where am I?
      run: ls .
    - name: Check TSAN
      run: nm -D ./build/test/simple_malloc_test | grep tsan
